### ISSUE TITLE
May Planning - 4.27.18 1/1

### ISSUE THREAD

**Issue by jraeglasgow** [jraeglasgow/Cam-1-1#5]
Hi @camwinsor ,

For our last one-on-one this month, I want to focus on a plan for May. Below is an outline of our monthly approach to success. I included specific goals you and I have discussed, connecting them to action items, as well as  feedback on last month to take into May. 

Please let me know if you have any questions and I look forward to reviewing this together Friday. Note, the outline is all that needs to be done by the meeting, I wanted to give you a full week to finish your assets so you can focus on the end of the month as well! 

-Jess
___________________________________________________________________________________________________________
**May Plan** 

**What**: Need 7 Meetings to Hit - 11 to Hit 150%
**Who**: Top 5 Accounts/ ESR that will get you to 150%
**When**: 
- Week 1 Activities 
- Week 2 Activities 
- Week 3 Activities
- Week 4 Activities 

**How**:
- Workflow: tools used, execution details: 
- cadences used / new logos you will bring in 

**Action Items**: 
- [ ] **Who**: Pick Top 5 Accounts/Rep and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th 
- [x] **When**: Map which activities to weeks to create plan to reach goal of 11 meetings (BHAG is to get promoted faster than any other EBR, how do you make this happen each week? 
- [x] **How**: outline ( high level example of how you are going to execute your plan for May) 

**April Feedback** 
- Good job leveraging existing account events to exceed your quota. 
- New logos - In looking at you as an EBR, if I am trying to see what you add (revenue, new logos, key account meetings) are you balanced across those three areas. For example, if 7/9 meetings in a month come from one account, how are you impacting new growth? (Think about it in terms of the metrics your next role will measure you by when comparing you to other candidates. (Hunter v. gatherer - what role do you want?) 
- Good job taking feedback and implementing, specifically when it comes to presenting yourself within the GitHub culture and as a leader on the team. 

**Assets**: 

- [SalesDev Account Tier/Mapping Template
](https://docs.google.com/spreadsheets/d/1W2FbnQrdPdLaCUsVQPJQq7YcUmN4IgAlRPA2xkqnlI4/edit#gid=1762991169)
- Master Issue Template 
## Company X

**SFDC** (link to Salesforce search for 'Company X')
**LinkedIn** 
**DiscoverOrg**
**Master spreadsheet**
**HQ:**  

#### VCS info
- **Current VCS:** 
- **Past GitHub trials:** 
- **Noticeable GitHub.com presence?** 

#### Context
- **Any similar customers?** (look for trends, key words, what's driving change?)
- **Any known tech initiatives?** (could be based on past conversations and/or on current info in the news)
- **Any known BUs? Which ones are we approaching?**
- **Key stakeholders:** (could be based on past conversations and/or on current info in the news)

#### 1st campaign: [who's being targetted]  
- **Why them?**
- **Target contacts:** (individuals, personas, or a specific BU)
  - ...

### Links to related Issues, Halp threads, SFDC notes
- ...

**Comment by camwinsor** [comment]
**May Plan** 

**What**: Need 7 Meetings to Hit - 11 to Hit 150%
**Who**: Top 5 Accounts/ ESR that will get you to 150%
**When**: 
- Week 1 Activities 
-- The first half of the week will be spent messaging event attendees and speakers, primarily at ServiceNow's internal event. There's also a few other relevant West coast events with speakers from top accounts. I've already compiled the target contact lists and written the vanilla templates so the week will start with a touch of customization and sending a 3-4 touch cadence that will run before, during and after the event.
-- I'll spend the second half of the week focused on researching high level personas at my top accounts for any published articles or evidence of participation in company movements (new initiatives, promotions, acquisitions/mergers, etc.) Sprinkled into the research process will be writing out the email cadences that will align any aforementioned recon and the most relevant messaging (roadmap, security, etc.)

- Week 2 Activities 
-- This is the busiest week for events with more than 4 tradeshows, one of which Brad will be attending. I hope I'll be spending a lot of time replying to emails, setting meetings, and milking respondents for additional contacts.
-- Any free time will be spent polishing & sending the whale messaging that I worked on in the previous week AND preparing for DXC's Buildathon (massive internal event) which takes place over the following two weeks.

- Week 3 Activities
--QBR will take up some of my time but outside that I'll be focusing on maximizing the value of any correspondence from the previous two weeks of messaging. 
--I have to coordinate with Newman on the best way to do it (also relevant: whether I actually attend DXC event), but I'll be sending out preliminary messages to relevant DXC contacts about our desire to meet up at Buildathon.
--I'll also begin drafting email cadences to a series of contacts from top accounts (that I've already accumulated) that are speakers at various events taking place end of May / beginning of June.

- Week 4 Activities 
--Email cadences (similar to previous; some tailoring, 3-4 touches before, during, and after) will start to run for the end of May events
--Hopefully I'll have started putting together a game plan for June and there will be action items to complete to that end. 

- All the weeks
--I'll be running through every contact I can find at Kaiser with pretty much the same message: you can use GHE for free, why aren't you, let's talk
--There is some opportunistic momentum at some accounts (NVIDIA, Veritas, Keysight, Arrow, Bio-Rad) from outreach this past month that I'll be keeping tabs on. Hopefully I can keep things moving with referrals and tips from those meetings. 
--I'll be focusing extra hard on getting referrals and tips from all connections made in May to carry through into the slower summer months. 

**How**:
- Workflow: The usual tools/workflow + looking for some ways that other hubbers are researching/prospecting/communicating (I'm always stalking correspondence in SFDC but I'm going to start picking out intriguing elements to review with originators)
- Cadences: blending roadmap & security value with targeted research on top personas for tailored messaging AND event messaging, customized for speakers and volume for attendees 😄 
- New logos: Arrow, Bio-Rad, Veritas, Keysight, NVIDIA
- Upsell: Kaiser, DXC, ServiceNow, Symantec

**Action Items**: 
- [ ] **Who**: Pick Top 5 Accounts/Rep and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th 
- [ ] **When**: Map which activities to weeks to create plan to reach goal of 11 meetings (BHAG is to get promoted faster than any other EBR, how do you make this happen each week? 
- [ ] **How**: outline ( high level example of how you are going to execute your plan for May)

**Comment by camwinsor** [comment]
[SalesDev Account Tiering Link](https://docs.google.com/spreadsheets/d/1seCDbS4TZ2d9BsZTjy1bYQjuGNgBSqhZq1iQ2BWHyyc/edit?usp=sharing)

**Comment by jraeglasgow** [comment]
@camwinsor going to close out this issue but wanted to checkin on the master issues, have you been able to do this for your reps and has it been helpful? Why or why not?

> Who: Pick Top 5 Accounts/Rep and Finish Master Issue and Tier Sheet for Each by EOD Monday, April 30th

Also, wanted to say you've improved on the two pieces of feedback below and should continue to focus on new logos and positioning yourself as a leader in these contexts. - Good job! 

>New logos - In looking at you as an EBR, if I am trying to see what you add (revenue, new logos, key account meetings) are you balanced across those three areas. For example, if 7/9 meetings in a month come from one account, how are you impacting new growth? (Think about it in terms of the metrics your next role will measure you by when comparing you to other candidates. (Hunter v. gatherer - what role do you want?)
Good job taking feedback and implementing, specifically when it comes to presenting yourself within the GitHub culture and as a leader on the team.
